///////////////////////////////////////////////////
// History, as it was on Wed Oct 30 21:59:40 2019.
///////////////////////////////////////////////////

// - 0:0:0 - (me)
// may history not repeat

// - 0:0:13.81 - (konstantinos)
"Hello"

// - 0:0:14.94 - (konstantinos)
"Hello"

// - 0:0:15.47 - (konstantinos)
"Hello"

// - 0:0:15.63 - (konstantinos)
"Hello"

// - 0:0:15.84 - (konstantinos)
"Hello"

// - 0:0:16.01 - (konstantinos)
"Hello"

// - 0:0:16.21 - (konstantinos)
"Hello"

// - 0:0:16.44 - (konstantinos)
"Hello"

// - 0:0:16.62 - (konstantinos)
"Hello"

// - 0:0:16.79 - (konstantinos)
"Hello"

// - 0:0:17.17 - (konstantinos)
"Hello"

// - 0:0:17.54 - (konstantinos)
"Hello"

// - 0:0:17.84 - (konstantinos)
"Hello"

// - 0:0:18.03 - (konstantinos)
"Hello"

// - 0:0:18.2 - (konstantinos)
"Hello"

// - 0:0:18.36 - (konstantinos)
"Hello"

// - 0:0:18.53 - (konstantinos)
"Hello"

// - 0:0:18.66 - (konstantinos)
"Hello"

// - 0:0:18.83 - (konstantinos)
"Hello"

// - 0:0:19.15 - (konstantinos)
"Hello"

// - 0:0:19.45 - (konstantinos)
"Hello"

// - 0:0:19.6 - (konstantinos)
"Hello"

// - 0:0:19.86 - (konstantinos)
"Hello"

// - 0:0:20.02 - (konstantinos)
"Hello"

// - 0:0:20.36 - (konstantinos)
"Hello"

// - 0:0:20.54 - (konstantinos)
"Hello"

// - 0:0:20.72 - (konstantinos)
"Hello"

// - 0:0:20.9 - (konstantinos)
"Hello"

// - 0:0:21.3 - (konstantinos)
"Hello"

// - 0:0:21.5 - (konstantinos)
"Hello"

// - 0:0:21.74 - (konstantinos)
"Hello"

// - 0:0:21.95 - (konstantinos)
"Hello"

// - 0:0:22.17 - (konstantinos)
"Hello"

// - 0:0:22.35 - (konstantinos)
"Hello"

// - 0:0:22.55 - (konstantinos)
"Hello"

// - 0:0:22.73 - (konstantinos)
"Hello"

// - 0:0:22.92 - (konstantinos)
"Hello"

// - 0:0:23.08 - (konstantinos)
"Hello"

// - 0:0:23.22 - (konstantinos)
"Hello"

// - 0:0:23.37 - (konstantinos)
"Hello"

// - 0:0:23.51 - (konstantinos)
"Hello"

// - 0:0:23.64 - (konstantinos)
"Hello"

// - 0:0:23.78 - (konstantinos)
"Hello"

// - 0:0:23.9 - (konstantinos)
"Hello"

// - 0:0:24.06 - (konstantinos)
"Hello"

// - 0:0:24.21 - (konstantinos)
"Hello"

// - 0:0:24.41 - (konstantinos)
"Hello"

// - 0:0:24.64 - (konstantinos)
"Hello"

// - 0:0:26.61 - (onur)
"hi"

// - 0:0:27.12 - (onur)
"hi"

// - 0:0:27.33 - (onur)
"hi"

// - 0:0:27.59 - (onur)
"hi"

// - 0:0:27.74 - (onur)
"hi"

// - 0:0:27.97 - (onur)
"hi"

// - 0:0:28.14 - (onur)
"hi"

// - 0:0:28.33 - (onur)
"hi"

// - 0:0:28.51 - (onur)
"hi"

// - 0:0:28.71 - (onur)
"hi"

// - 0:0:28.95 - (onur)
"hi"

// - 0:0:29.1 - (onur)
"hi"

// - 0:0:34.5 - (konstantinos)
"Hello Alberto"

// - 0:0:34.59 - (onur)
"hi"

// - 0:0:34.82 - (onur)
"hi"

// - 0:0:34.99 - (onur)
"hi"

// - 0:0:35.2 - (onur)
"hi"

// - 0:0:35.37 - (onur)
"hi"

// - 0:0:35.56 - (onur)
"hi"

// - 0:0:35.74 - (onur)
"hi"

// - 0:0:35.85 - (konstantinos)
"Hello Alberto"

// - 0:0:35.92 - (onur)
"hi"

// - 0:0:36.1 - (onur)
"hi"

// - 0:0:36.29 - (onur)
"hi"

// - 0:0:36.5 - (onur)
"hi"

// - 0:0:36.65 - (onur)
"hi"

// - 0:0:36.91 - (onur)
"hi"

// - 0:0:37.11 - (onur)
"hi"

// - 0:0:37.36 - (konstantinos)
"Hello Alberto"

// - 0:0:38 - (konstantinos)
"Hello Alberto"

// - 0:0:38.58 - (konstantinos)
"Hello Alberto"

// - 0:0:39.26 - (konstantinos)
"Hello Alberto"

// - 0:0:39.75 - (konstantinos)
"Hello Alberto"

// - 0:0:40.19 - (konstantinos)
"Hello Alberto"

// - 0:0:40.79 - (konstantinos)
"Hello Alberto"

// - 0:0:45.79 - (konstantinos)
"Hello Alberto"

// - 0:0:47.64 - (konstantinos)
"Hello Alberto"

// - 0:0:49.05 - (konstantinos)
"Hello Alberto"

// - 0:0:49.36 - (konstantinos)
"Hello Alberto"

// - 0:0:49.58 - (konstantinos)
"Hello Alberto"

// - 0:0:49.75 - (konstantinos)
"Hello Alberto"

// - 0:0:58.44 - (konstantinos)
"Hello Alberto"

// - 0:0:59.03 - (konstantinos)
"Hello Alberto"

// - 0:0:59.39 - (konstantinos)
"Hello Alberto"

// - 0:0:59.62 - (konstantinos)
"Hello Alberto"

// - 0:1:1.53 - (konstantinos)
"Hello Alberto"

// - 0:1:2.07 - (konstantinos)
"Hello Alberto"

// - 0:1:2.28 - (konstantinos)
"Hello Alberto"

// - 0:1:2.68 - (konstantinos)
"Hello Alberto"

// - 0:1:3.33 - (konstantinos)
"Hello Alberto"

// - 0:1:15.96 - (konstantinos)
"Hello Alberto"

// - 0:1:16.26 - (konstantinos)
"Hello Alberto"

// - 0:1:16.48 - (konstantinos)
"Hello Alberto"

// - 0:1:18.8 - (konstantinos)
"Hello Alberto"

// - 0:1:26.05 - (konstantinos)
"Hello Alberto"

// - 0:1:26.39 - (konstantinos)
"Hello Alberto"

// - 0:1:26.61 - (konstantinos)
"Hello Alberto"

// - 0:1:28.21 - (konstantinos)
"Hello Alberto"

// - 0:1:28.45 - (konstantinos)
"Hello Alberto"

// - 0:1:28.66 - (konstantinos)
"Hello Alberto"

// - 0:1:28.88 - (konstantinos)
"Hello Alberto"

// - 0:1:35.99 - (konstantinos)
"Hello Alberto"

// - 0:1:36.44 - (konstantinos)
"Hello Alberto"

// - 0:1:37.28 - (konstantinos)
"Hello Alberto"

// - 0:1:38.13 - (konstantinos)
"Hello Alberto"

// - 0:1:38.37 - (konstantinos)
"Hello Alberto"

// - 0:1:38.54 - (konstantinos)
"Hello Alberto"

// - 0:1:38.76 - (konstantinos)
"Hello Alberto"

// - 0:1:38.94 - (konstantinos)
"Hello Alberto"

// - 0:1:39.14 - (konstantinos)
"Hello Alberto"

// - 0:2:1.08 - (konstantinos)
100.do{ "Hello Alberto"}

// - 0:2:7.04 - (onur)
"hi"

// - 0:2:7.47 - (onur)
"hi"

// - 0:2:7.75 - (onur)
"hi"

// - 0:2:8.55 - (onur)
"hi"

// - 0:2:8.94 - (onur)
"hi"

// - 0:2:9.19 - (onur)
"hi"

// - 0:2:9.44 - (onur)
"hi"

// - 0:2:9.7 - (onur)
"hi"

// - 0:2:9.94 - (onur)
"hi"

// - 0:2:10.2 - (onur)
"hi"

// - 0:2:10.73 - (onur)
"hi"

// - 0:2:11.09 - (onur)
"hi"

// - 0:2:11.64 - (onur)
"hi"

// - 0:2:12.84 - (onur)
"hi"

// - 0:2:13.05 - (onur)
"hi"

// - 0:2:13.28 - (onur)
"hi"

// - 0:2:13.45 - (onur)
"hi"

// - 0:2:13.69 - (onur)
"hi"

// - 0:2:13.93 - (onur)
"hi"

// - 0:2:14.15 - (onur)
"hi"

// - 0:2:14.39 - (onur)
"hi"

// - 0:2:14.62 - (onur)
"hi"

// - 0:2:14.82 - (onur)
"hi"

// - 0:2:15.04 - (onur)
"hi"

// - 0:2:15.32 - (onur)
"hi"

// - 0:2:15.55 - (onur)
"hi"

// - 0:2:15.79 - (onur)
"hi"

// - 0:2:16.02 - (onur)
"hi"

// - 0:2:16.25 - (onur)
"hi"

// - 0:2:16.54 - (onur)
"hi"

// - 0:2:16.73 - (onur)
"hi"

// - 0:2:16.96 - (onur)
"hi"

// - 0:2:17.18 - (onur)
"hi"

// - 0:2:17.42 - (onur)
"hi"

// - 0:2:17.69 - (onur)
"hi"

// - 0:2:17.94 - (onur)
"hi"

// - 0:2:18.07 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:18.13 - (onur)
"hi"

// - 0:2:18.37 - (onur)
"hi"

// - 0:2:18.57 - (onur)
"hi"

// - 0:2:18.8 - (onur)
"hi"

// - 0:2:18.95 - (onur)
"hi"

// - 0:2:19.12 - (onur)
"hi"

// - 0:2:19.23 - (onur)
"hi"

// - 0:2:19.38 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:19.42 - (onur)
"hi"

// - 0:2:19.56 - (onur)
"hi"

// - 0:2:19.69 - (onur)
"hi"

// - 0:2:19.9 - (onur)
"hi"

// - 0:2:20.55 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:20.84 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:21.82 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:22.32 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:22.44 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:22.52 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:22.6 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:22.69 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:22.77 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:23.23 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:25.54 - (konstantinos)
{10.do{ "Hello Alberto".postln}}

// - 0:2:38.89 - (onur)
"hi"

// - 0:2:39.22 - (onur)
"hi"

// - 0:2:39.48 - (onur)
"hi"

// - 0:2:39.75 - (onur)
"hi"

// - 0:2:39.98 - (onur)
"hi"

// - 0:2:40.29 - (onur)
"hi"

// - 0:2:40.47 - (onur)
"hi"

// - 0:2:40.7 - (onur)
"hi"

// - 0:2:40.95 - (onur)
"hi"

// - 0:2:41.26 - (onur)
"hi"

// - 0:2:41.46 - (onur)
"hi"

// - 0:2:41.71 - (onur)
"hi"

// - 0:2:41.97 - (onur)
"hi"

// - 0:2:42.28 - (onur)
"hi"

// - 0:2:42.69 - (onur)
"hi"

// - 0:2:43.02 - (onur)
"hi"

// - 0:2:43.5 - (onur)
"hi"

// - 0:2:43.72 - (onur)
"hi"

// - 0:2:43.92 - (onur)
"hi"

// - 0:2:44.19 - (onur)
"hi"

// - 0:2:44.4 - (onur)
"hi"

// - 0:2:44.62 - (onur)
"hi"

// - 0:2:44.85 - (onur)
"hi"

// - 0:2:45.11 - (onur)
"hi"

// - 0:2:45.35 - (onur)
"hi"

// - 0:2:45.57 - (onur)
"hi"

// - 0:2:45.81 - (onur)
"hi"

// - 0:2:45.98 - (onur)
"hi"

// - 0:2:46.18 - (onur)
"hi"

// - 0:2:46.47 - (onur)
"hi"

// - 0:2:46.62 - (onur)
"hi"

// - 0:2:46.83 - (onur)
"hi"

// - 0:2:47.08 - (onur)
"hi"

// - 0:2:47.27 - (onur)
"hi"

// - 0:2:47.51 - (onur)
"hi"

// - 0:2:47.76 - (onur)
"hi"

// - 0:2:48 - (onur)
"hi"

// - 0:2:48.22 - (onur)
"hi"

// - 0:2:48.47 - (onur)
"hi"

// - 0:2:48.69 - (onur)
"hi"

// - 0:2:48.97 - (onur)
"hi"

// - 0:2:49.22 - (onur)
"hi"

// - 0:2:49.42 - (onur)
"hi"

// - 0:2:49.66 - (onur)
"hi"

// - 0:2:49.87 - (onur)
"hi"

// - 0:2:50.07 - (onur)
"hi"

// - 0:2:51.52 - (onur)
"hi"

// - 0:2:52.86 - (onur)
"hi"

// - 0:2:53.3 - (onur)
"hi"

// - 0:2:53.58 - (onur)
"hi"

// - 0:2:53.9 - (onur)
"hi"

// - 0:2:54.13 - (onur)
"hi"

// - 0:2:54.53 - (onur)
"hi"

// - 0:2:54.59 - (onur)
"hi"

// - 0:2:54.81 - (onur)
"hi"

// - 0:2:55.02 - (onur)
"hi"

// - 0:2:55.24 - (onur)
"hi"

// - 0:2:55.47 - (onur)
"hi"

// - 0:2:55.72 - (onur)
"hi"

// - 0:2:56 - (onur)
"hi"

// - 0:2:56.22 - (onur)
"hi"

// - 0:2:56.45 - (onur)
"hi"

// - 0:2:56.71 - (onur)
"hi"

// - 0:2:56.95 - (onur)
"hi"

// - 0:2:57.48 - (onur)
"hi"

// - 0:2:57.74 - (onur)
"hi"

// - 0:2:57.98 - (onur)
"hi"

// - 0:2:58.49 - (onur)
"hi"

// - 0:2:58.72 - (onur)
"hi"

// - 0:2:58.95 - (onur)
"hi"

// - 0:2:59.22 - (onur)
"hi"

// - 0:2:59.43 - (onur)
"hi"

// - 0:2:59.66 - (onur)
"hi"

// - 0:2:59.92 - (onur)
"hi"

// - 0:3:0.17 - (onur)
"hi"

// - 0:3:0.5 - (onur)
"hi"

// - 0:3:0.84 - (onur)
"hi"

// - 0:3:1.13 - (onur)
"hi"

// - 0:3:1.31 - (onur)
"hi"

// - 0:3:1.64 - (onur)
"hi"

// - 0:3:1.97 - (onur)
"hi"

// - 0:3:2.12 - (onur)
"hi"

// - 0:3:2.43 - (onur)
"hi"

// - 0:3:2.77 - (onur)
"hi"

// - 0:3:2.95 - (onur)
"hi"

// - 0:3:3.22 - (onur)
"hi"

// - 0:3:3.69 - (onur)
"hi"

// - 0:3:4.12 - (onur)
"hi"

// - 0:3:4.36 - (onur)
"hi"

// - 0:3:4.67 - (onur)
"hi"

// - 0:3:4.95 - (onur)
"hi"

// - 0:3:5.22 - (onur)
"hi"

// - 0:3:5.64 - (onur)
"hi"

// - 0:3:6 - (onur)
"hi"

// - 0:3:6.32 - (onur)
"hi"

// - 0:3:6.7 - (onur)
"hi"

// - 0:3:7 - (onur)
"hi"

// - 0:3:7.37 - (onur)
"hi"

// - 0:3:7.59 - (onur)
"hi"

// - 0:3:7.82 - (onur)
"hi"

// - 0:3:8.1 - (onur)
"hi"

// - 0:3:8.34 - (onur)
"hi"

// - 0:3:8.63 - (onur)
"hi"

// - 0:3:8.9 - (onur)
"hi"

// - 0:3:9.14 - (onur)
"hi"

// - 0:3:9.47 - (onur)
"hi"

// - 0:3:9.76 - (onur)
"hi"

// - 0:3:9.99 - (onur)
"hi"

// - 0:3:10.27 - (onur)
"hi"

// - 0:3:10.48 - (onur)
"hi"

// - 0:3:10.73 - (onur)
"hi"

// - 0:3:10.98 - (onur)
"hi"

// - 0:3:11.23 - (onur)
"hi"

// - 0:3:11.52 - (onur)
"hi"

// - 0:3:11.78 - (onur)
"hi"

// - 0:3:12.05 - (onur)
"hi"

// - 0:3:12.32 - (onur)
"hi"

// - 0:3:12.56 - (onur)
"hi"

// - 0:3:12.81 - (onur)
"hi"

// - 0:3:12.98 - (onur)
"hi"

// - 0:3:13.18 - (onur)
"hi"

// - 0:3:13.35 - (onur)
"hi"

// - 0:3:13.53 - (onur)
"hi"

// - 0:3:13.73 - (onur)
"hi"

// - 0:3:13.93 - (onur)
"hi"

// - 0:3:14.17 - (onur)
"hi"

// - 0:3:14.43 - (onur)
"hi"

// - 0:3:14.63 - (onur)
"hi"

// - 0:3:14.92 - (onur)
"hi"

// - 0:3:15.13 - (onur)
"hi"

// - 0:3:15.47 - (onur)
"hi"

// - 0:3:15.68 - (onur)
"hi"

// - 0:3:15.94 - (onur)
"hi"

// - 0:3:16.37 - (onur)
"hi"

// - 0:3:16.6 - (onur)
"hi"

// - 0:3:16.87 - (onur)
"hi"

// - 0:3:17.08 - (onur)
"hi"

// - 0:3:17.34 - (onur)
"hi"

// - 0:3:17.55 - (onur)
"hi"

// - 0:3:17.77 - (onur)
"hi"

// - 0:3:17.99 - (onur)
"hi"

// - 0:3:18.22 - (onur)
"hi"

// - 0:3:18.48 - (onur)
"hi"

// - 0:3:18.67 - (onur)
"hi"

// - 0:4:38.25 - (void)
//!! hellloooo

// - 0:4:46.14 - (onur)
"hi"

// - 0:4:46.64 - (onur)
"hi"

// - 0:4:51.32 - (onur)
(
Tdef(\ODtext1, {
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 110, 220, 440].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \klankinger,
			\freq: frq,
			\sustain: sus * 4,
			\amp: 0.3,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \klankinger,
			\freq: (frq * 5) / 4,
			\sustain: sus * 4,
			\amp: 1,
			server: serv
		).play;


		([0.5, 0.25, 0.75, 1 ].choose).wait;
	})
}).play;
)

// - 0:5:12.52 - (selo)
//!! hey

// - 0:5:18.4 - (void)
//!! hellllloooooooo

// - 0:5:29.4 - (void)
({
	88.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%100 * 100 + 1000, decay: 0.9, amp: 0.5, pan: 0, server: s).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
)

// - 0:12:23.5 - (void)
//!! hellllloooooooo

// - 0:12:34.75 - (selo)
(
// hatRit
Tdef(\hatRit, {
	40.do({ arg i;
		(instrument: "hatXLine",
			\server: ~servReg.choose,
			\freq: rrand(5000, 8000),
			\decay: 0.1,
			\amp: 0.125
		).play;

		(0.125 * (1.05 ** i)).wait;
	});
}).play;
)

// - 0:12:39.74 - (void)
({
	88.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%100 * 100 + 1000, decay: 0.9, amp: 0.5, pan: 0, server: s).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
)

// - 0:31:40.48 - (void)
//!! welcome

// - 0:33:16.24 - (konstantinos)
"hellp"

// - 1:14:39.75 - (selo)
//!! hey

// - 1:15:0.8 - (onur)
//!! hello world

// - 1:15:56.66 - (adc)
(
// axisOfEvil
Tdef(\axisOfEvil).set(\hits, 20);
Tdef(\axisOfEvil, { |e|
	e.hits.do({ |i|
			(
				instrument: \grainXLine,
				server: ~servReg.choose,
	 			freq: exprand(200, 20000),
	 			sustain: 0.1,
	 			amp: 2

	 		).play;

		(rrand(1, 4) * 0.01).wait;
	});
}).play(quant: 0);
)

// - 1:16:11.37 - (adc)
Tdef(\axisOfEvil).set(\hits, 4).play;

// - 1:16:13.41 - (void)
({
	88.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%100 * 100 + 1000, decay: 0.9, amp: 0.5, pan: 0, server: s).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
)

// - 1:16:18.43 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 05.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \grain,
					\freq: frq * 1.9,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:16:25.61 - (adc)
Tdef(\axisOfEvil).set(\hits, 50).play;

// - 1:16:26.57 - (void)
(
Tdef(\hatRit, {
	40.do({ arg i;
		(instrument: "hatXLine",
			\server: ~servReg.choose,
			\freq: rrand(5000, 8000),
			\decay: 0.1,
			\amp: 0.125
		).play;
		(0.125 * (1.05 ** i)).wait;
	});
}).play;
)

// - 1:16:27.48 - (onur)
(
Tdef( 'ODRythmic1' , {
	loop {
		( instrument: \bsfm,
		  freq: rrand(3500, 2) * 110,
		  sustain: 1,
			amp:0.25,
		  server: ~servReg.choose
		).play;
		[0.25, 0.125, 0.125 ].wchoose([0.1, 0.2, 2.0 ] / 4).wait;
	}
} ).play;
)

// - 1:16:29.05 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 05.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \grain,
					\freq: frq * 1.9,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:16:31.96 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 05.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \grain,
					\freq: frq * 1.9,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:16:38.73 - (adc)
(
Tdef( 'gliso' , {
	100.do({ arg i;
		(
			instrument: \ana1,
			instrument: \glisson,
			\freq: i % 15 * -4 + 200 * 12,
			\freq2: i % 7 * 20 + 200 * 4,
			\sustain: 0.04,
			\amp: 0.25,
			\server:  ~servReg.values @@ i
		).postln.play;

		[0.1, 0.2, 0.4].choose.wait;
	});
} ).play;
)

// - 1:16:45.91 - (onur)
(
// Glitchrox1
Tdef(\ODGlitchNoise, {
	var chooseFr =  { exprand(30, 1000) } ;
	var startf = chooseFr.value;
	var stoptf = chooseFr.value;
	500.do({ arg i;
		var unt = { exprand(3000, 1200) } ! 4;

		16.do({ arg where;
			var dt = rrand(1, 3.0);

			(	instrument: \kabelScahden,
				server: ~servReg.choose,
				freq2: startf,
				freq: stoptf,
				sustain: dt * 1.5,
				amp: 0.1,
			).play;
			dt.wait;
			startf = stoptf;
			stoptf = chooseFr.value;
		});
	});
}).stop.play;
)

// - 1:16:54.67 - (adc)
(
Tdef( 'gliso' , {
	100.do({ arg i;
		(
			instrument: \ana1,
			instrument: \glisson,
			\freq: i % 15 * -4 + 200 * 12,
			\freq2: i % 7 * 20 + 200 * 4,
			\sustain: 0.04,
			\amp: 0.25,
			\server:  ~servReg.values @@ i
		).postln.play;

		[0.1, 0.2, 0.4].choose.wait;
	});
} ).play;
)

// - 1:17:8.25 - (onur)
(

(
Tdef(\ODMelo1, {
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 164, 329, 668, 2080].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \gong_0,
			\freq: frq,
			\sustain: sus * 2,
			\amp: 0.3,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \gong_0,
			\freq: frq + 5,
			\sustain: sus * 2,
			\amp: 0.3,
			server: serv
		).play;


		([1,0.5,0.25].choose).wait;
	})
}).play;
);

(
Tdef(\ODMelo2, {
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 164, 329, 668, 2080].choose;
		sus = 0.4;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \pfeifchen,
			\freq: frq,
			\sustain: sus * 2,
			\amp: 0.3,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \pfeifchen,
			\freq: frq + 5,
			\sustain: sus * 2,
			\amp: 0.3,
			server: serv
		).play;


		([2,0.5,1].choose).wait;
	})
}).play;
)

)

// - 1:17:8.64 - (void)
(
Tdef(\dirZ, {
	var dt, freq=3333 + 100.rand, serv = ~servReg.values.choose;
	dt = Pn(Pgeom(0.001, 1.2, 30)).asStream;

	1000.do {|i|
		if(i%33 ==0){freq = i % 10 + 1 * 1000};
		if(i%59 ==0){serv = ~servReg.values.wrapAt(i).postcln };

		(	instrument: \grain,
			server: serv,
			out: [0,1],
			amp: 1/2,
			freq: freq + 2.0.rand2.midicps,
			sustain: 0.001 * rrand(1, 2.0)
		).play;
		dt.next.wait
	};
}).play
)

// - 1:17:9.49 - (adc)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.values.choose,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:17:17.4 - (void)
(
Tdef( 'tim' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4 ];
	var sustain = 0.2;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': [130,840], 'mod_index': 3.0, 'out': 0, 'instrument': 'SOStom',
				'pan': 0.0, 'amp': 0.1,
				server: s,
				sustain:sustain,
				'beater_noise_level': 0.025, 'decay': 1, 'mod_freq': 1.0 ).play;


			(dt / 2).wait;
		}
	}
} ).play;
)

// - 1:17:28.23 - (onur)
(
Tdef(\ODMelo3, {
	4.do({ arg isx;
		Routine({
			8.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 110, 440, 165].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \gong_3,
					\freq: frq,
					\sustain: sus,
					\amp: 0.2,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \gong_4,
					\freq: frq * 2,
					\sustain: sus / 1.5,
					\amp: 0.2,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		2.wait;
	});
}).play;
)

// - 1:17:29.67 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.values.choose,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:17:34.45 - (adc)
~addrBook.peers.do(_.sendMsg("/oo_i", "s.volume = 0"));

// - 1:17:35.64 - (void)
(
Tdef( 'tim' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4 ];
	var sustain = 0.2;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': [130,840], 'mod_index': 3.0, 'out': 0, 'instrument': 'SOStom',
				'pan': 0.0, 'amp': 0.1,
				server: s,
				sustain:sustain,
				'beater_noise_level': 0.025, 'decay': 1, 'mod_freq': 1.0 ).play;


			(dt / 2).wait;
		}
	}
} ).stop;
)

// - 1:17:39.31 - (void)
(
Tdef( 'microbeat' , {
	120.do {
		(instrument: "hatXLine", freq: rrand(30, 50) * 30, decay: 0.003,
			amp: 0.7, server: ~servReg.choose).play;
		[0.25, 0.125, 0.125, 0.0625].wchoose([0.1, 0.2, 0.7]).wait;
	}
} ).play;
)

// - 1:17:41.44 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \grain,
					\freq: frq * 1.9,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:17:42.39 - (adc)
(
Tdef( 'gliso' , {
	100.do({ arg i;
		(
			instrument: \ana1,
			instrument: \glisson,
			\freq: i % 15 * -4 + 200 * 12,
			\freq2: i % 7 * 20 + 200 * 4,
			\sustain: 0.04,
			\amp: 0.25,
			\server:  ~servReg.values @@ i
		).postln.play;

		[0.1, 0.2, 0.4].choose.wait;
	});
} ).play;
)

// - 1:17:42.97 - (void)
(
SynthDef(\UCAstutter, { | freq = 222, trigFreq = 0.5,  crushRate = 1, spread = 1, amp = 0.5,
	revSize = 1, revDecay = 1, revMix = 0.40, atk = 0.01, rel = 6|
	var sig, pha, trig, env ;
	trig = Impulse.ar(trigFreq);
	pha = Phasor.kr(trig, trigFreq/crushRate);
	env = EnvGen.ar(Env.perc(atk, rel), doneAction:2 );
	sig = {Saw.ar((freq), pha) + Rand(50)}!6;
	sig = FreeVerb.ar(Splay.ar(sig, spread).sin, 0.33, revSize, revDecay).flop.sum.tanh;
	sig = sig * env * amp;
	Out.ar(0, sig);
}).add
)

// - 1:17:45.15 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.values.choose,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:17:48.47 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \grain,
					\freq: frq * 1.12,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:17:51.15 - (adc)
(
Tdef(\denseFlimm, {
	100.do({ arg i;
		(instrument: \amacherFlimmern,

			\freq: i % 5 * 300 + 1000,
			\freq2: i % 7 * 200 + 2000,
			\sustain: 01.05,
			\amp: 0.5,
			\server:  ~servReg.values.choose
		).play;

		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:17:54.98 - (void)
(
Pdef(\stutter,
	Pbind(
		\instrument, \UCAstutter,
		\dur, Pseq([0.25, 0.125, 0.125], inf),
		\atk, 0.0001,
		\rel, 0.5,
		\amp, 0.75,
		\freq, Pseq([1000, 2000, 5000], inf),
		\trigFreq, Pwhite(1,12),
		\server, Pfunc({(~s.values).choose}),
		\crushRate, Pwhite(50,400),
	)
).play;
)

// - 1:17:56.45 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:18:5.78 - (adc)
(
// tief, 3:2
Tdef(\low3_2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 200 + 500,
			\freq2: i % 7 * 300 + 2500,
			\sustain: 0.01,
			\server: ~servReg.values.choose
			).play;
		(1 / (i % 12 + 10)).wait;
		// 0.75.wait;
	});
}).play(quant: 0);
)

// - 1:18:10.62 - (onur)
(
// Glitchrox1
Tdef(\ODGlitchNoise, {
	var chooseFr =  { exprand(30, 1000) } ;
	var startf = chooseFr.value;
	var stoptf = chooseFr.value;
	500.do({ arg i;
		var unt = { exprand(3000, 1200) } ! 4;

		16.do({ arg where;
			var dt = rrand(1, 3.0);

			(	instrument: \kabelScahden,
				server: ~servReg.choose,
				freq2: startf,
				freq: stoptf,
				sustain: dt * 1.5,
				amp: 0.1,
			).play;
			dt.wait;
			startf = stoptf;
			stoptf = chooseFr.value;
		});
	});
}).stop.play;
)

// - 1:18:11.13 - (void)
(instrument: \xf_tanh, gain: 10, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:18:13.39 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \grain,
					\freq: frq * 1.12,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:18:22.22 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.konstantinosvasilakos,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:18:23.55 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.konstantinosvasilakos,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:18:24.02 - (void)
(
SynthDef(\gbman,
	{
		|atk = 0.25, decay = 0.3, sus = 1, rel = 0.5, freq = 1000, out = 0, amp = 0.4
		a = 1.1 , b = 0.3, c = 0.13, xi = 0, yi = 2.1, m = 1, gate = 1, wet =(-20) dry = 1|
		var sig, env;
		env = EnvGen.kr(Env.adsr(atk, decay, sus, rel, [5,0,-5]), gate, doneAction: 2);
		sig = GbmanL.ar(
			freq: freq,
			xi: xi,
			yi: yi,
			mul: 0.25);
		sig = env * sig * amp;
		sig = Splay.ar(sig);
		Out.ar(out, sig * dry);
}).add;
)

// - 1:18:25.36 - (onur)
(
Tdef( 'ODRise' , {
	var servs, serv, lasti;
	Pn(Pseries(48, 1, 24), inf).do { |note, i|
		servs = ~servReg.values;
		lasti = servs.indexOf(serv) ? -1;
		serv = servs.wrapAt(lasti + 1);
		8.do { |j|
			(midinote: note, instrument: [\rain, \gong_2, \gong_3].wrapAt(i+j), server: serv, dur: 0.25, amp: 0.5, out: j).play;
			0.125.wait;
		}
	};
} ).play;
)

// - 1:18:27.69 - (adc)
(
Tdef(\hartBraten, {		// harter Braten !
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:18:27.69 - (void)
(
Pdef( \gbmanChimes,
	Pbind(
		\instrument, \gbman,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\ctranspose, 43.25,
		\degree, Prand([0,36], inf),
		\a, Prand([0,36], inf),
		\b, Prand([0.2,1], inf),
		\xi, Pwhite(5.0, 12.0),
		\yi, Pwhite(0.0, 4.0),
		\atk, 4,
		\rel, 4,
		\amp, 0.75,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:18:29.6 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.adc,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:18:31.52 - (adc)
Tdef(\hartBraten).stop;

// - 1:18:34.32 - (void)
(
Pdef( \gbmanChimes,
	Pbind(
		\instrument, \gbman,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\ctranspose, 43.25,
		\degree, Prand([0,36], inf),
		\a, Prand([0,36], inf),
		\b, Prand([0.2,1], inf),
		\xi, Pwhite(5.0, 12.0),
		\yi, Pwhite(0.0, 4.0),
		\atk, 4,
		\rel, 4,
		\amp, 0.55,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:18:36.2 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \bsfm,
					\freq: frq * 1.12,
					\sustain: sus / 5.3,
					\amp: 5,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:18:38.32 - (void)
(
~servReg.do { |s|
	(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.12, drift: 0.8, rate: 0.3,
		addAction: 1, group: 1, server: s).play;
};
);

// - 1:18:43.55 - (void)
(instrument: \xf_tanh, gain: 10, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:18:44.89 - (adc)
(
Tdef(\hartBraten, {		// harter Braten !
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg.choose;
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:18:47.89 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \bsfm,
					\freq: frq * 1.12,
					\sustain: sus / 6.3,
					\amp: 2,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:18:48.79 - (void)
(
SynthDef(\linCong,
	{
		|atk = 0.25, decay = 0.3, sus = 1, rel = 0.5, freq = 1000, out = 0, amp = 0.4
		a = 1.1 , b = 0.3, c = 0.13, xi = 0, yi = 2.1, m = 1, gate = 1, wet =(-20) dry = 1|
		var sig, env;
		env = EnvGen.kr(Env.adsr(atk, decay, sus, rel, [5,0,-5]), gate, doneAction: 2);
		sig = LinCongL.ar(
			freq: freq,
			a: (a * 2.5).max(1.1),
			c: c,
			m: m,
			xi: xi,
			mul: 0.25);
		sig = env * sig * amp;
		sig = LeakDC.ar(sig.tanh);
		sig = Splay.ar(sig);
		Out.ar(out, sig * dry);
}).add;
)

// - 1:18:49.13 - (adc)
Tdef(\hartBraten).stop;

// - 1:18:51.67 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.adc,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:18:55.11 - (onur)
(
// STRESS
Tdef(\ODSturmundDrang, {
	var chooseFr =  { exprand(300, 400) } ;
	var startf = chooseFr.value;
	var stoptf = chooseFr.value;
	500.do({ arg i;
		var unt = { exprand(3000, 1200) } ! 8;

		42.do({ arg where;
			var dt = rrand(1, 3.0);

			(	instrument: \rain,
				server: ~servReg.choose,
				freq2: startf,
				freq: stoptf,
				sustain: dt * 1.5,
				amp: 0.05,
			).play;
			dt.wait;
			startf = stoptf;
			stoptf = chooseFr.value;
		});
	});
}).stop.play;
)

// - 1:19:5.41 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,24], inf),
		\ctranspose, 42,
		\yi, Pwhite(0.0, 4.0),
		\atk, 3,
		\rel, 6,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:19:7.12 - (void)
Pdef(\white).play(t, quant: -1);

// - 1:19:7.92 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:19:14 - (void)
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:19:17.06 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \ana2,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:26.07 - (void)
(
Tdef(\hatRit, {
	40.do({ arg i;
		(instrument: "hatXLine",
			\server: ~servReg.choose,
			\freq: rrand(5000, 8000),
			\decay: 0.1,
			\amp: 0.125
		).play;
		(0.125 * (1.05 ** i)).wait;
	});
}).stop;
)

// - 1:19:27.79 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:31 - (onur)
(
SynthDef.new(\Onursyn, {
	arg out = 0, freq = 220;
		var sig, sig2, sig3, sigout, env;
				sig = SinOsc.ar(freq);
				sig2 = SinOsc.ar(freq);
				sig3 = Saw.ar(freq);
				env = EnvGen.kr(Env.new([0.01,1,0.2,0.5,0.01],[0.2,0.3,1,0.5],[\sine,\sine,\sine,-5]), doneAction: 2);
			sigout = sig + sig2 + sig3 * env * \amp.kr(0.2);
			sigout = BLowPass.ar(sigout, freq: 300, rq: 1.4, mul: 1, add: 0);
			sigout = FreeVerb.ar(sigout, mix: 0.6, room: 0.32, damp: 0.6, mul: 1, add: 0);
		sigout = Pan2.ar(sigout, LFNoise1.kr(1).range(-1,1));
	Out.ar(out,sigout);
}).add;
)

// - 1:19:35.24 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:35.48 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \grain,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:37.41 - (void)
(
Tdef(\hartBraten, {		// harter Braten !
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 4000, 7000, 9999].choose;
		sus = 0.1;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 0.25,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \grainlet,
			\freq: frq / 4,
			\sustain: sus * 0.5,
			\amp: 0.25,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:19:39.14 - (onur)
(
p = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[2];
	).play;

z = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[1];
).play;
n = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server, ~s.values[0];
)
.play;
)

// - 1:19:47.17 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6800, 9890].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \grain,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:50.48 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: ~servReg.adc
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:54 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6800, 9890].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.9,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \grain,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:19:58.73 - (onur)
(
Tdef(\ODtext1, {
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 110, 220, 440].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \klankinger,
			\freq: frq,
			\sustain: sus * 4,
			\amp: 0.3,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \klankinger,
			\freq: (frq * 5) / 4,
			\sustain: sus * 4,
			\amp: 1,
			server: serv
		).play;


		([0.5, 0.25, 0.75, 1 ].choose).wait;
	})
}).play;
)

// - 1:20:0.72 - (void)
(
Pdef(\stutter,
	Pbind(
		\instrument, \UCAstutter,
		\dur, Pseq([0.25, 0.125, 0.125], inf),
		\atk, 0.0001,
		\rel, 0.5,
		\amp, 0.75,
		\freq, Pseq([4000, 2500, 500], inf),
		\trigFreq, Pwhite(1,12),
		\server, Pfunc({(~s.values).choose}),
		\crushRate, Pwhite(50,400),
	)
).play;
)

// - 1:20:8.64 - (void)
(
Pdef(\stutter,
	Pbind(
		\instrument, \UCAstutter,
		\dur, Pseq([0.25, 0.125, 0.125], inf),
		\atk, 0.0001,
		\rel, 0.5,
		\amp, 0.75,
		\freq, Pseq([400, 250, 500], inf),
		\trigFreq, Pwhite(1,12),
		\server, Pfunc({(~s.values).choose}),
		\crushRate, Pwhite(50,400),
	)
).play;
)

// - 1:20:9.61 - (onur)
(
Tdef(\ODText2, {
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 66, 138, 271, 520, 112, 224, 888, 1048].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \klankinger,
			\freq: frq,
			\sustain: sus * 10,
			\amp: 1,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \klankinger,
			\freq: (frq * 5) / 4,
			\sustain: sus * 10,
			\amp: 0.4,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.08).wait;
	})
}).play;
)

// - 1:20:11.77 - (adc)
(
Tdef( 'cristil' , {
	500.do({ arg i;

		6.do({ arg where;
			(instrument: "grainXLRev",
				freq: (i * rrand(20, 200) + 10000).fold(10000, 30000),
				sustain: 0.1,
				where: ~servReg.wrapAt(where)
			).play;
			0.01.wait;
		});
	});
} );
);

// - 1:20:13.6 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(15, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.5,
					\sustain: sus / 1.5,
					\amp: 2.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:20:13.89 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: ~servReg.onut
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:20:16.22 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: ~servReg.onur
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:20:19.01 - (onur)
(
Tdef(\ODText3, {
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 66, 138, 271, 520, 112, 224, 888, 1048].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \Onursyn,
			\freq: frq,
			\sustain: sus * 10,
			\amp: 1,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \klankinger,
			\freq: (frq * 5) / 4,
			\sustain: sus * 10,
			\amp: 0.4,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.08).wait;
	})
}).play;
)

// - 1:20:22.2 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,18], inf),
		\ctranspose, 42,
		\yi, Pwhite(0.0, 4.0),
		\atk, 2,
		\rel, 6,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:20:22.37 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(15, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.5,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:20:34.24 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(45, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.5,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:20:39.64 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(25, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.5,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:20:44.62 - (void)
(
Pdef( \gbmanChimes,
	Pbind(
		\instrument, \gbman,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\ctranspose, 43.25,
		\degree, Prand([0,36], inf),
		\a, Prand([0,36], inf),
		\b, Prand([0.2,1], inf),
		\xi, Pwhite(5.0, 12.0),
		\yi, Pwhite(0.0, 4.0),
		\atk, 4,
		\rel, 4,
		\amp, 0.35,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:20:46.24 - (void)
Pdef(\gbmanChimes).play(t, quant: -1);

// - 1:20:48.98 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(25, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.7,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:20:55.96 - (adc)
(
// wahwah pedal with distortion
~servReg.do { |s|
	(instrument: \xf_wah, addAction: 1, dur: exprand(3, 10), server: s).play;
};
);

// - 1:20:57.39 - (void)
(instrument: \xf_tanh, gain: 10, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:21:2.88 - (konstantinos)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(25, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.7,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:21:3.26 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(25, 100)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4500, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.7,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:21:7.8 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:21:15.15 - (void)
(
Tdef(\dirZ, {
	var dt, freq=444 + 100.rand, serv = ~servReg.values.choose;
	dt = Pn(Pgeom(0.001, 1.2, 30)).asStream;

	1000.do {|i|
		if(i%33 ==0){freq = i % 10 + 1 * 1000};
		if(i%59 ==0){serv = ~servReg.values.wrapAt(i).postcln };

		(	instrument: \grain,
			server: serv,
			out: [0,1],
			amp: 1/2,
			freq: freq + 2.0.rand2.midicps,
			sustain: 0.001 * rrand(1, 2.0)
		).play;
		dt.next.wait
	};
}).play
)

// - 1:21:19.52 - (void)
(
Tdef( 'ti' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4, 1, 0.5, 0.5, 1 ];
	var sustain = 0.1;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': 250, 'mod_index': 5.0, 'out': 0, 'instrument': 'SOSkick',
				'pan': 0.0, 'amp': 0.15,
				server: s,

				'beater_noise_level': 0.025, 'decay': 0.4, 'mod_freq': 5.0 ).play;


			(dt / 8).wait;
		}
	}
} ).play;
)

// - 1:21:23.7 - (void)
(
Tdef( 'tim' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4 ];
	var sustain = 0.2;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': [130,840], 'mod_index': 3.0, 'out': 0, 'instrument': 'SOStom',
				'pan': 0.0, 'amp': 0.1,
				server: s,
				sustain:sustain,
				'beater_noise_level': 0.025, 'decay': 1, 'mod_freq': 1.0 ).play;


			(dt / 2).wait;
		}
	}
} ).stop;
)

// - 1:21:30.36 - (void)
(
Tdef( 'tim' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4 ];
	var sustain = 0.2;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': [130,840], 'mod_index': 3.0, 'out': 0, 'instrument': 'SOStom',
				'pan': 0.0, 'amp': 0.1,
				server: s,
				sustain:sustain,
				'beater_noise_level': 0.025, 'decay': 1, 'mod_freq': 1.0 ).play;


			(dt / 2).wait;
		}
	}
} ).play;
)

// - 1:21:32.37 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..120) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.1
		)
	)
).play;
)

// - 1:21:38.58 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..120) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.1
		)
	)
).play;
)

// - 1:21:39.31 - (adc)
(instrument: 'feedDriftComb2', freq: 3500, sustain: 5, amp: 0.3, out: 1).play;

// - 1:21:41.08 - (onur)
(
// STRESS
Tdef(\ODSturmundDrang2, {
	var chooseFr =  { exprand(300, 400) } ;
	var startf = chooseFr.value;
	var stoptf = chooseFr.value;
	500.do({ arg i;
		var unt = { exprand(3000, 1200) } ! 8;

		42.do({ arg where;
			var dt = rrand(1, 3.0);

			(	instrument: \UCAstutter,
				server: ~servReg.choose,
				freq2: startf,
				freq: stoptf,
				sustain: dt * 1.5,
				amp: 0.05,
			).play;
			dt.wait;
			startf = stoptf;
			stoptf = chooseFr.value;
		});
	});
}).stop.play;
)

// - 1:21:43.86 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..120) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.9
		)
	)
).play;
)

// - 1:21:51.84 - (adc)
(
// urlaut 2 high
Pdef(\ur4,
	Pstutter(
	Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\fundA, Pseq((50, 60..110), inf) * 5,
			\fundZ, Pseq((50, 60..120), inf) * 3,
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf),
			\legato, 10 ** Pbrown(-1, -0.5),
			\lag, Pfunc({ [0, 1, 2, 3].scramble * 0.02 }),
			\server, ~servReg.choose
		)
	)
).play;
)

// - 1:21:54.42 - (void)
(
~servReg.do { |s|
	(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.12, drift: 0.8, rate: 0.3,
		addAction: 1, group: 1, server: s).play;
};
);

// - 1:21:55.76 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..140) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.130, 0.130, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.9
		)
	)
).play;
)

// - 1:21:57.59 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: ~servReg.onur
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:21:58.84 - (void)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(5, 15), server: s).play;

// - 1:22:5.29 - (onur)
(instrument: \xf_wah, addAction: 1, dur: 6, server: s).play;

// - 1:22:7.17 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu".reverse, inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..140) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.130, 0.130, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.9
		)
	)
).play;
)

// - 1:22:9.7 - (void)
(instrument: \xf_tanh, gain: 10, dur: 50, addAction: 1, group: 1, server: s).play;

// - 1:22:10.89 - (adc)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..20) + 40).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.5, 0.05, 0.05)),
			\amp, 0.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:22:25.49 - (void)
(
Tdef( 'ti' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4, 1, 0.5, 0.5, 1 ];
	var sustain = 0.1;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': 250, 'mod_index': 5.0, 'out': 0, 'instrument': 'SOSkick',
				'pan': 0.0, 'amp': 0.15,
				server: s,

				'beater_noise_level': 0.025, 'decay': 0.4, 'mod_freq': 5.0 ).play;


			(dt / 8).wait;
		}
	}
} ).stop;
)

// - 1:22:27.31 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: ~servReg.onur
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:22:33.42 - (konstantinos)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6600, 9800].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.5,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \ana1,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: ~servReg.onur
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:22:35.95 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 0.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:22:38.33 - (void)
(
Tdef( 'tim' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4 ];
	var sustain = 0.2;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': [260,1680], 'mod_index': 3.0, 'out': 0, 'instrument': 'SOStom',
				'pan': 0.0, 'amp': 0.1,
				server: s,
				sustain:sustain,
				'beater_noise_level': 0.025, 'decay': 1, 'mod_freq': 1.0 ).play;


			(dt / 2).wait;
		}
	}
} ).play;
)

// - 1:22:38.43 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.adc,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:22:41.11 - (adc)
(
// always up
Pdef(\ur2,
	Pstutter(
	Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, Pfunc( { ~servReg.choose }),
			\fundA, 20,
			\fundZ, Pseq((50, 60..120), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf),
			\legato, 10 ** Pbrown(-1, -0.5)
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:22:44.03 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 0.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:22:47.07 - (void)
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:22:49.12 - (onur)
~s

// - 1:22:59.13 - (adc)
(
Tdef( 'uio2' , {
	loop {
		~servReg.do { |sv|
			(instrument: \glisson, freq: exprand(10000, 200) * 4, freq2: exprand(100, 200) ,
				sustain: 2, amp: 0.2,
				server: sv
			).play;
			0.4.wait;
		};
	}
} ).play;
);

// - 1:23:2.84 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6800, 9890].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.9,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \grain,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 0.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:23:9.08 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6800, 9890].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.9,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \grain,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:23:10.11 - (onur)
(
p = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[0];
	).play;

z = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[1];
).play;
n = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server, ~s.values[0];
)
.play;
)

// - 1:23:22.92 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:23:23.95 - (adc)
(
{
	inf.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%7 * 100 + 6000, decay: 0.2, amp: 0.5, pan: 0, server: s.postln).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
);

// - 1:23:28.64 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:23:37.23 - (onur)
//!! going voc

// - 1:23:43.57 - (onur)
(
// Voc3
Pdef(\ODRoboVoc3,
	Pstutter(
	Prand([1, 8, 1, 1, 3, 5, 7], inf),
		Pbind(
			\vowelA, Pseq("aaooaii", inf),
			\vowelZ, Pseq("aaou".reverse, inf),
			\type, \urlaut,
			\fundA, Pseq((57, 60..110), inf),
			\fundZ, Pseq((57, 60..120), inf),
			\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
			\legato, 5 ** Pbrown(-1, -0.5),
			\server,~s.values[0];
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:23:44.74 - (selo)
(
// always up
Pdef(\ur2,
	Pstutter(
	Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu", inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose,
			\fundA, 20,
			\fundZ, Pseq((50, 60..120), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf),
			\legato, 10 ** Pbrown(-1, -0.5)
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:23:44.83 - (adc)
(
{
	inf.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%7 * 100 + 6000, decay: 0.2, amp: 0.5, pan: 0, server: s).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
);

// - 1:23:50.65 - (konstantinos)
//!! Okay

// - 1:23:55.32 - (onur)
(
// Voc2
Pdef(\ODRoboVoc2,
	Pstutter(
	Prand([1, 1, 1, 1, 3, 5, 7], inf),
		Pbind(
			\vowelA, Pseq("eii", inf),
			\vowelZ, Pseq("ooioio".reverse, inf),
			\type, \urlaut,
			\fundA, Pseq((57, 60..110), inf),
			\fundZ, Pseq((57, 60..120), inf),
			\dur, Prand([0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf),
			\legato, 5 ** Pbrown(-1, -0.5),
			\server,~s.values[2];
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:24:9.21 - (onur)
(
// Voc1
Pdef(\ODRoboVoc,
	Pstutter(
	Prand([1, 1, 1, 1, 3, 5, 7], inf),
		Pbind(
			\vowelA, Pseq("aaooaaii", inf),
			\vowelZ, Pseq("aaooeeii".reverse, inf),
			\type, \urlaut,
			\fundA, Pseq((57, 60..110), inf),
			\fundZ, Pseq((57, 60..120), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf),
			\legato, 5 ** Pbrown(-1, -0.5),
			\server,~s.values[3];
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:24:11.05 - (adc)
(instrument: 'feedDriftComb3', freq: 300, sustain: 5, amp: 3, out: 1).play;

// - 1:24:17 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu".reverse, inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..140) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.130, 0.130, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.9
		)
	)
).play;
)

// - 1:24:19.55 - (adc)
(instrument: 'feedDriftComb3', freq: 300, sustain: 5, amp: 0.3, out: 1).play;

// - 1:24:25.54 - (adc)
(instrument: 'feedDriftComb3', freq: 30, sustain: 5, amp: 0.3, out: 1).play;

// - 1:24:28.01 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 0.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:24:28.67 - (adc)
(instrument: 'feedDriftComb3', freq: 3, sustain: 5, amp: 0.3, out: 1).play;

// - 1:24:33.21 - (adc)
(instrument: 'feedDriftComb3', freq: 0.2, sustain: 5, amp: 0.3, out: 1).play;

// - 1:24:47.47 - (void)
(
Pdef( \gbmanChimes,
	Pbind(
		\instrument, \gbman,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\ctranspose, 31,
		\degree, Prand([0,36], inf),
		\a, Prand([0,36], inf),
		\b, Prand([0.2,1], inf),
		\xi, Pwhite(5.0, 12.0),
		\yi, Pwhite(0.0, 4.0),
		\atk, 0.001,
		\rel, 0.6,
		\amp, 0.35,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:24:54.64 - (onur)
(
// Voc2
Pdef(\ODRoboVoc2,
	Pstutter(
	Prand([1, 1, 1, 1, 3, 5, 7], inf),
		Pbind(
			\vowelA, Pseq("eii", inf),
			\vowelZ, Pseq("ooioio".reverse, inf),
			\type, \urlaut,
			\fundA, Pseq((57, 60..110), inf),
			\fundZ, Pseq((57, 60..120), inf),
			\dur, Prand([0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf),
			\legato, 5 ** Pbrown(-1, -0.5),
			\server,~s.values[2];
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:24:57.48 - (onur)
(
// Voc3
Pdef(\ODRoboVoc3,
	Pstutter(
	Prand([1, 8, 1, 1, 3, 5, 7], inf),
		Pbind(
			\vowelA, Pseq("aaooaii", inf),
			\vowelZ, Pseq("aaou".reverse, inf),
			\type, \urlaut,
			\fundA, Pseq((57, 60..110), inf),
			\fundZ, Pseq((57, 60..120), inf),
			\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
			\legato, 5 ** Pbrown(-1, -0.5),
			\server,~s.values[0];
		//	\sustain, 0.1
		)
	)
).play;
)

// - 1:25:4.6 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:25:15.23 - (selo)
({
	var win, texts, newtext, index = 0;
	texts = Array.newClear(20); //Array of executed codes,

	{
		win = Window("Code Display")
		.background_(Color.black).alpha_(0.9)
		.alwaysOnTop_(true)
		.view.keyDownAction_(
			{|v, c, m , u, k|
				switch(k,
					$6, {win.fullScreen},//z key to fullscreen
					$7, {win.endFullScreen}//x key to end fullscreen
			)}
		);
		win.front;
	}.defer;

	newtext = {|num, newCode, fadeTime=30|
		var color;
		color = Color(*{1.0.rand}!3);
		{  //New text object
			texts[num] = StaticText(win, Rect(640.rand,400.rand,640,400))
			.string_(newCode)
			.stringColor_(Color.white)
			.font_(Font("Courier",size:20)).align_(\topLeft)}.defer;

		{  // right after new text created, fade out
			256.do{|i|
				if(win.isClosed.not){
					{texts[num].stringColor_(color.alpha_(i.linlin(0,255,1,0)))}.defer;
				};
				(fadeTime / 256).wait;
			}
		}.fork;
	};

	Tdef(\blp, {var txt, oldTxt, index=0;
		loop{
			txt = History.lines[0];
			if((txt === oldTxt).not){
				if(win.isClosed.not){
					index = index + 1;
					newtext.value(index%texts.size, txt.last.asString ++ "\n\n");
					//	txt.last.postln;
				}
			};
			oldTxt = txt;
			win.refresh;
			(1/30).wait;
		};
	}).clock_(AppClock).play

	// this.preProcessor = {|code| newtext.value(index%texts.size, code.asString ++ "\n\n");
	// 	index = index + 1;
	// 	code

	//var addr = NetAddr.new("127.0.0.1", 12000); //OSC forwarder
	/*OSCdef(\cR, { |msg, time, tidalAddr|
	var latency = time - Main.elapsedTime;
	msg = msg ++ ["time", time, "latency", latency];
	newtext.value(index%texts.size, msg.asString ++ "\n\n");
	//addr.sendBundle(latency, msg)
	}, '/play2').fix;*/

}.fork
)

// - 1:25:16.01 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.adc,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:25:16.28 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.adc,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:25:16.91 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.adc,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:25:19.82 - (void)
(
Pdef( \gbmanChimes,
	Pbind(
		\instrument, \gbman,
		\dur, 0.25,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\ctranspose, 31,
		\degree, Prand([0,36], inf),
		\a, Prand([0,36], inf),
		\b, Prand([0.2,1], inf),
		\xi, Pwhite(5.0, 12.0),
		\yi, Pwhite(0.0, 4.0),
		\atk, 0.001,
		\rel, 0.6,
		\amp, 0.35,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:25:23.47 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.onur,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:25:24.38 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \bsfm,
					\freq: frq * 1.12,
					\sustain: sus / 6.3,
					\amp: 2,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:25:40.69 - (selo)
(	///same same but diffrent   SELF VARYing
Tdef(\enigmaSameDiff, {
	4.do({ arg isx;
		Routine({ var serv, luv =  rrand(0.1, 20);
			(rrand(45, 55)).do({ arg i; var frq, sus, dir, tim;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4500, 6600, 8800].choose/(isx+1) /luv;
				sus = 0.001 * (isx+1);

				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \grain,
					\freq: frq,
					\sustain: sus,
					\amp: 0.1,
					server: serv
				).play;

				(instrument: \grain,
					\freq: frq * 1.7,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;


				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:25:43.89 - (adc)
(instrument: 'feedDriftComb3', freq: 0.5, sustain: 5, amp: 0.3, out: 1).play;

// - 1:25:46.52 - (adc)
(instrument: 'feedDriftComb3', freq: 3, sustain: 5, amp: 0.3, out: 1).play;

// - 1:25:48.08 - (void)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(5, 15), server: s).play;

// - 1:25:50.67 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:25:53.93 - (konstantinos)
//!! feedback synth please

// - 1:26:0.21 - (void)
(
SynthDef(\feedBack,
	{
		|atk = 0.25, decay = 0.3, sus = 1, rel = 0.5, freq = 1000, out = 0, amp = 0.25,
		a = 1.1 , b = 0.3, c = 0.13, xi = 0, yi = 2.1, m = 1, gate = 1, wet =(-20) dry = 1|
		var sig, env;
		env = EnvGen.kr(Env.adsr(atk, decay, sus, rel, [5,0,-5]), gate, doneAction: 2);
		sig = FBSineC.ar(
			freq: freq,
			im: 1,
			fb: 0.1,
			a: (a + 1.1).min(1.9),
			c: c * 3,
			xi: xi,
			yi: xi,
			mul: 0.25);
		sig = env * sig * amp;
		sig = LPF.ar(sig, 2000);
		sig = BRF.ar(sig, 250);
		sig = LeakDC.ar(sig.tanh);
		sig = Splay.ar(sig);
		Out.ar(out, sig * dry);
}).add;
)

// - 1:26:3.79 - (onur)
(
p = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[0];
	).play;

z = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[1];
).play;
n = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server, ~s.values[2];
)
.play;
)

// - 1:26:19.38 - (adc)
(
Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[0];
	).play;
);

// - 1:26:19.5 - (void)
//!! sent

// - 1:26:25.74 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6800, 9890].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.9,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \feedbackDriftcomb,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:26:27.4 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \feedback,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.onur,
			\amp: 1
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:26:33.82 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \feedback,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.onur,
			\amp: 1.5
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:26:35.64 - (adc)
(
Tdef( 'looool2' , {
	var servs, serv, lasti;
	Pn(Pseries(2, 1, 15), inf).do { |note, i|
		servs = ~servReg.values;
		lasti = servs.indexOf(serv) ? -1;
		serv = servs.wrapAt(lasti + 1);
		(midinote: i%3 * 6 + note, instrument: \fooA, server: serv, dur: 0.30, amp: 0.5).play;
		0.1025.wait;
	};
	2.3.wait;
} );
);

// - 1:26:37.09 - (selo)
(
Tdef(\bratPath, {|ev|		// harter Braten !
	var frq, sus, serv, path;
	var startNode = q.nodes.choose;

	inf.do{|jj|
		var endNode = q.nodes.choose;
		var detune = 0.4.rand2+1;
		sus = 0.001 + 0.1.linrand;

		path = startNode.pathTo(endNode);
		// path = [startNode] ++ path;
		path.size.postln;
		path.collect(_.name).postln;

		ev.endNode = endNode;

		path.do{|node, ii|
			serv = ~servReg[node.name.postcs];
			25.do({ arg i;
				frq = [ 140, 500, 6800, 9890].choose * rrand(1, 1.02) * detune;
				(
					instrument: \grain,
					\freq: frq,
					\decay: sus,
					\sustain: sus,
					\amp: 0.9,
					server: serv
				).play;
				0.01.wait;
				(
					instrument: \feedDriftcomb,
					\freq: frq / 1.5,
					\sustain: sus / 1.5,
					\amp: 5.5,
					server: serv
				).play;
				([0.5, 0.1, 2, 1/8 ].choose * 0.1).wait;
			})

		};
		startNode = endNode;
	}

}).play;
)

// - 1:26:38.29 - (konstantinos)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \feedback,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.04,
			\server: ~servReg.onur,
			\amp: 0.5
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:26:44.88 - (void)
(
SynthDef(\UCAstutter, { | freq = 222, trigFreq = 0.5,  crushRate = 1, spread = 1, amp = 0.5,
	revSize = 1, revDecay = 1, revMix = 0.40, atk = 0.01, rel = 6|
	var sig, pha, trig, env ;
	trig = Impulse.ar(trigFreq);
	pha = Phasor.kr(trig, trigFreq/crushRate);
	env = EnvGen.ar(Env.perc(atk, rel), doneAction:2 );
	sig = {Saw.ar((freq), pha) + Rand(50)}!6;
	sig = FreeVerb.ar(Splay.ar(sig, spread).sin, 0.99, revSize, revDecay).flop.sum.tanh;
	sig = sig * env * amp;
	Out.ar(0, sig);
}).add
)

// - 1:26:47.08 - (onur)
(
SynthDef.new(\Onursyn, {
	arg out = 0, freq = 220;
		var sig, sig2, sig3, sigout, env;
				sig = SinOsc.ar(freq);
				sig2 = SinOsc.ar(freq);
				sig3 = Saw.ar(freq);
				env = EnvGen.kr(Env.new([0.01,1,0.2,0.5,0.01],[0.2,0.3,1,0.5],[\sine,\sine,\sine,-5]), doneAction: 2);
			sigout = sig + sig2 + sig3 * env * \amp.kr(0.2);
			sigout = BLowPass.ar(sigout, freq: 300, rq: 1.4, mul: 1, add: 0);
			sigout = FreeVerb.ar(sigout, mix: 0.6, room: 0.32, damp: 0.6, mul: 1, add: 0);
		sigout = Pan2.ar(sigout, LFNoise1.kr(1).range(-1,1));
	Out.ar(out,sigout);
}).add;
)

// - 1:26:47.7 - (void)
(
Pdef(\stutter,
	Pbind(
		\instrument, \UCAstutter,
		\dur, Pseq([0.25, 0.125, 0.125], inf),
		\atk, 0.0001,
		\rel, 0.5,
		\amp, 0.75,
		\freq, Pseq([400, 250, 500], inf),
		\trigFreq, Pwhite(1,12),
		\server, Pfunc({(~s.values).choose}),
		\crushRate, Pwhite(50,400),
	)
).play;
)

// - 1:26:48.02 - (selo)
(
// urlaut w pauses, up/down
Pdef(\ur1,
	Pstutter(
	Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\voiceA, \alto,
			\vowelA, Pseq("aeeiou".scramble, inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\amp, 0.7,
			\fundA, Pseq((50, 60..110), inf) * 0.2,
			\fundZ, Pseq((50, 60..120), inf) * 0.5,
			\server, ~servReg.choose,
			\dur, Prand([ 4, 2, 1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf) * 0.5,
			\legato, 20 ** Pbrown(-1, -0)
		,	\sustain, 0.1
		)
	)
).play;
)

// - 1:26:51.43 - (onur)
(
p = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[0];
	).play;

z = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server,~s.values[1];
).play;
n = Pbind(
	\instrument, \Onursyn,
	\dur, Prand([0.25, 0.125, 0.125, 0.125], inf),
	\midinote, Pseq((57, 60..120), inf),
	\server, ~s.values[2];
)
.play;
)

// - 1:26:56.3 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:27:5.11 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:27:9.44 - (adc)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.05.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:27:13.37 - (void)
({
	88.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%200 * 100 + 1000, decay: 0.9, amp: 0.5, pan: 0, server: s).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
)

// - 1:27:33.26 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:27:34.23 - (void)
(
~servReg.do { |s|
	(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.12, drift: 0.8, rate: 0.3,
		addAction: 1, group: 1, server: s).play;
};
);

// - 1:27:36.2 - (selo)
(
Tdef(\denseFlimm, {
	100.do({ arg i;
		(instrument: \amacherFlimmern,

			\freq: i % 5 * 300 + 1000,
			\freq2: i % 7 * 200 + 2000,
			\sustain: 01.05,
			\amp: 0.5,
			\server:  ~servReg.values.choose
		).play;

		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:27:40.3 - (void)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(5, 15), server: s).play;

// - 1:27:40.43 - (konstantinos)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.05.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:27:43.05 - (selo)
(
Tdef(\denseFlimm, {
	300.do({ arg i;
		(instrument: \amacherFlimmern,

			\freq: i % 5 * 300 + 1000,
			\freq2: i % 7 * 200 + 2000,
			\sustain: 01.05,
			\amp: 0.5,
			\server:  ~servReg.values.choose
		).play;

		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:27:48.43 - (konstantinos)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 2.5,
			server: serv
		).play;

		0.05.wait;
		serv = ~servReg[\adc];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.5,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:27:48.93 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:27:58.89 - (void)
(
SynthDef(\gbman,
	{
		|atk = 0.25, decay = 0.3, sus = 1, rel = 0.5, freq = 1000, out = 0, amp = 0.4
		a = 1.1 , b = 0.3, c = 0.13, xi = 0, yi = 2.1, m = 1, gate = 1, wet =(-20) dry = 1|
		var sig, env;
		env = EnvGen.kr(Env.adsr(atk, decay, sus, rel, [5,0,-5]), gate, doneAction: 2);
		sig = GbmanL.ar(
			freq: freq/6,
			xi: xi,
			yi: yi,
			mul: 0.25);
		sig = env * sig * amp;
		sig = Splay.ar(sig);
		Out.ar(out, sig * dry);
}).add;
)

// - 1:28:2.35 - (selo)
(
// tief, 3:2
Tdef(\low3_2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 200 + 500,
			\freq2: i % 7 * 300 + 2500,
			\sustain: 0.01,
			\server: ~servReg.values.choose
			).play;
		(1 / (i % 12 + 10)).wait;
		// 0.75.wait;
	});
}).play(quant: 0);
)

// - 1:28:3.38 - (adc)
(
{
	inf.do{ |i|
		~servReg.do{|s, j|

			var in = [\hatXLRev, \hatXLine] @@ j;
			(instrument: in, freq: i%7 * 100 + 6000, decay: 0.2, amp: 0.5, pan: 0, server: s).play;
			(0.2 - (i/100)).fold(0.001, 1).wait;
		}
	}
}.fork;
);

// - 1:28:9.88 - (adc)
(
Tdef( 'uio2' , {
	loop {
		~servReg.do { |sv|
			(instrument: \glisson, freq: exprand(10000, 200) * 4, freq2: exprand(100, 200) ,
				sustain: 2, amp: 0.2,
				server: sv
			).play;
			0.4.wait;
		};
	}
} ).play;
);

// - 1:28:13.8 - (adc)
~servReg

// - 1:28:27.4 - (selo)
(
// tief, 3:2
Tdef(\low3_2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 200 + 700,
			\freq2: i % 7 * 300 + 2500,
			\sustain: 0.01,
			\server: ~servReg.values.choose
			).play;
		(1 / (i % 12 + 10)).wait;
		// 0.75.wait;
	});
}).play(quant: 0);
)

// - 1:28:31.52 - (selo)
(
// tief, 3:2
Tdef(\low3_2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 200 + 700,
			\freq2: i % 7 * 300 + 2500,
			\sustain: 0.09,
			\server: ~servReg.values.choose
			).play;
		(1 / (i % 12 + 10)).wait;
		// 0.75.wait;
	});
}).play(quant: 0);
)

// - 1:28:33.45 - (void)
(
Tdef( 'uio2' , {
	loop {
		~servReg.do { |sv|
			(instrument: \glisson, freq: exprand(10000, 200) * 4, freq2: exprand(100, 200) ,
				sustain: 2, amp: 0.2,
				server: sv
			).play;
			0.4.wait;
		};
	}
} ).play;
);

// - 1:28:36.6 - (selo)
(
// hochTicks
Tdef(\highTick, {
	100.do({ arg i;
		(instrument: [ \grainXLine, \grainXLRev ].choose,
			\freq: i % 20 * 200 + 4000 + 200.rand,
			\sustain: 0.005,
			\amp: 1,
			\server: ~servReg.values.choose
		).play;
		 [2, 1.5, 1.25, 0.75].choose.wait;
	});
}).play(quant: 0);
)

// - 1:28:42.54 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:28:46.99 - (selo)
(
// tief, 3:2
Tdef(\low3_2, {
	1.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 200 + 700,
			\freq2: i % 7 * 300 + 2500,
			\sustain: 0.09,
			\server: ~servReg.values.choose
			).play;
		(1 / (i % 12 + 10)).wait;
		// 0.75.wait;
	});
}).play(quant: 0);
)

// - 1:28:48.36 - (adc)
(
// schen cristalline
Tdef(\cristil, {
	500.do({ arg i;

		6.do({ arg where;
			(instrument: "grainXLRev",
				freq: (i * rrand(20, 200) + 10000).fold(10000, 30000),
				sustain: 0.1,
				where: ~servReg.wrapAt(where)
			).play;
			0.01.wait;
		});
	});
}).stop.play;
)

// - 1:28:55.77 - (adc)
(
// schen cristalline
Tdef(\cristil, {
	500.do({ arg i;

		6.do({ arg where;
			(instrument: "grainXLRev",
				freq: (i * rrand(20, 200) + 10000).fold(10000, 30000),
				sustain: 0.1,
				where: ~servReg.wrapAt(where)
			).play;
			0.01.wait;
		});
	});
}).stop.play;
)

// - 1:28:57.58 - (void)
(
Tdef( 'uio2' , {
	loop {
		~servReg.do { |sv|
			(instrument: \glisson, freq: exprand(10000, 200) * 4, freq2: exprand(100, 200) ,
				sustain: 2, amp: 0.2,
				server: sv
			).play;
			0.4.wait;
		};
	}
} ).stop;
);

// - 1:29:0.6 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:29:10.55 - (konstantinos)
(
Tdef( 'mode_canon_1' , { |ev|
	var motif = [ [ 0, 1, 2 ], [ 0, 2, 1 ], [ 1, 0, 2 ], [ 1, 2, 0 ], [ 2, 0, 1 ], [ 2, 1, 0 ] ];
	ev.scaleName = ~commons[\canonScale];
	ev.scale = Scale.at(ev.scaleName);

	loop {
		// wait a bit before starting to play
		(~addrBook.size * 2).rand.wait;
		Tdef('mode_canon_1').set(\dt, 1/[2, 3, 4, 5, 6, 8].choose);
		Tdef('mode_canon_1').set(\octave, [4, 5, 6].choose);
		Tdef('mode_canon_1').set(\transpose, 8.rand2);
		Tdef('mode_canon_1').set(\inst, Tdef('mode_canon_1').get(\syndefs).choose);

		(0..7).do { |i|
			motif.do { |trip, j|
				trip.do { |note, k|
					(instrument:
						ev.inst,
						scale: ev.scale,
						degree: note + i + ev.transpose,
						octave: ev.octave,
						dur: 0.5,
						amp: ev.amp
					).play;
					ev.dt.wait;
				};
				ev.dt.wait;
			};
			(ev.dt * 2).wait;
		};
	};
} );
);

// - 1:29:11.18 - (selo)
(
Tdef(\dirZ, {
	var dt, freq=3333, serv = ~servReg.values.choose;
	dt = Pn(Pgeom(0.001, 1.2, 30)).asStream;

	1.do {|i|
		if(i%33 ==0){freq = i % 10 + 2 * 1000};
		if(i%59 ==0){serv = ~servReg.values.wrapAt(i).postcln };

		(	instrument: \grain,
			server: serv,
			out: [0,1],
			amp: 1,
			freq: freq,
			sustain: 0.001 * rrand(1, 2.0)
		).play;
		dt.next.wait
	};
}).play
)

// - 1:29:19.98 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:20.7 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:21.17 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:21.22 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,18], inf),
		\ctranspose, 30,
		\yi, Pwhite(0.0, 4.0),
		\atk, 2,
		\rel, 6,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:29:21.83 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:22.4 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:22.88 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:24.68 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:24.83 - (selo)
(
Tdef(\dirZ, {
	var dt, freq=3333, serv = ~servReg.values.choose;
	dt = Pn(Pgeom(0.001, 1.2, 30)).asStream;

	3.do {|i|
		if(i%33 ==0){freq = i % 10 + 2 * 1000};
		if(i%59 ==0){serv = ~servReg.values.wrapAt(i).postcln };

		(	instrument: \grain,
			server: serv,
			out: [0,1],
			amp: 1,
			freq: freq,
			sustain: 0.001 * rrand(1, 4.0)
		).play;
		dt.next.wait
	};
}).play
)

// - 1:29:25.95 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:26.89 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.1, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:31.88 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,18], inf),
		\ctranspose, 30,
		\yi, Pwhite(0.0, 4.0),
		\atk, 4,
		\rel, 8,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:29:32.96 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:29:36.22 - (adc)
~servReg.choose

// - 1:29:37.01 - (adc)
~servReg.choose

// - 1:29:37.45 - (adc)
~servReg.choose

// - 1:29:41.89 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,18], inf),
		\ctranspose, 30,
		\yi, Pwhite(0.2, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:29:42.47 - (adc)
(instrument: \kabelScahden, freq: [51, 50] * rrand(0.3, 1.0), sustain: 10, amp: 0.5, server: ~servReg.choose).play;

// - 1:29:48.3 - (void)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(5, 15), server: s).play;

// - 1:29:56.69 - (konstantinos)
(
Tdef( 'mode_canon_1' , { |ev|
	var motif = [ [ 0, 1, 2 ], [ 0, 2, 1 ], [ 1, 0, 2 ], [ 1, 2, 0 ], [ 2, 0, 1 ], [ 2, 1, 0 ] ];
	ev.scaleName = ~commons[\canonScale];
	ev.scale = Scale.at(ev.scaleName);

	loop {
		// wait a bit before starting to play
		(~addrBook.size * 2).rand.wait;
		Tdef('mode_canon_1').set(\dt, 1/[2, 3, 4, 5, 6, 8].choose);
		Tdef('mode_canon_1').set(\octave, [4, 5, 6].choose);
		Tdef('mode_canon_1').set(\transpose, 8.rand2);
		Tdef('mode_canon_1').set(\inst, Tdef('mode_canon_1').get(\syndefs).choose);

		(0..7).do { |i|
			motif.do { |trip, j|
				trip.do { |note, k|
					(instrument:
						ev.inst,
						scale: ev.scale,
						degree: note + i + ev.transpose,
						server: ~servReg[\adc],
						octave: ev.octave,
						dur: 0.5,
						amp: ev.amp
					).play;
					ev.dt.wait;
				};
				ev.dt.wait;
			};
			(ev.dt * 2).wait;
		};
	};
} );
);

// - 1:30:6.68 - (selo)
(
// revHatAccel
Tdef(\revHatAccel, {
	200.do({ arg i;
		(instrument: "gong_0",
			\server: ~servReg.choose,
			\freq: exprand(8000, 16000),
			\decay: 0.02,
			\amp: rrand(3.1, 3.25)
		).play;
		(0.1 * (0.99 ** i)).wait;
	});
}).play;
)

// - 1:30:6.76 - (void)
//!! textural ?

// - 1:30:7.69 - (konstantinos)
(
Tdef( 'mode_canon_1' , { |ev|
	var motif = [ [ 0, 1, 2 ], [ 0, 2, 1 ], [ 1, 0, 2 ], [ 1, 2, 0 ], [ 2, 0, 1 ], [ 2, 1, 0 ] ];
	ev.scaleName = ~commons[\canonScale];
	ev.scale = Scale.at(ev.scaleName);

	loop {
		// wait a bit before starting to play
		(~addrBook.size * 2).rand.wait;
		Tdef('mode_canon_1').set(\dt, 1/[2, 3, 4, 5, 6, 8].choose);
		Tdef('mode_canon_1').set(\octave, [4, 5, 6].choose);
		Tdef('mode_canon_1').set(\transpose, 8.rand2);
		Tdef('mode_canon_1').set(\inst, Tdef('mode_canon_1').get(\syndefs).choose);

		(0..7).do { |i|
			motif.do { |trip, j|
				trip.do { |note, k|
					(instrument:
						ev.inst,
						scale: ev.scale,
						degree: note + i + ev.transpose,
						server: ~servReg.choose,
						octave: ev.octave,
						dur: 0.5,
						amp: ev.amp
					).play;
					ev.dt.wait;
				};
				ev.dt.wait;
			};
			(ev.dt * 2).wait;
		};
	};
} );
);

// - 1:30:10.38 - (adc)
(
// urlaut w pauses, up/down
Pdef(\ur1,
	Pstutter(
	Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\voiceA, \alto,
			\vowelA, Pseq("aeeiou".scramble, inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\amp, 0.7,
			\fundA, Pseq((50, 60..110), inf) * 0.2,
			\fundZ, Pseq((50, 60..120), inf) * 0.5,
			\server, Pfunc( { ~servReg.choose }),
			\dur, Prand([ 4, 2, 1, 0.5, 0.25, 0.25, 0.125, 0.125, 0.125, 0.125], inf) * 0.5,
			\legato, 20 ** Pbrown(-1, -0)
		,	\sustain, 0.1
		)
	)
).play;
)

// - 1:30:18.38 - (adc)
//!! yes, textural

// - 1:30:21.77 - (onur)
//!! yea maybe move to texture

// - 1:30:22.57 - (konstantinos)
//!! yes

// - 1:30:23.87 - (void)
(
Tdef(\dirZ, {
	var dt, freq=444 + 100.rand, serv = ~servReg.values.choose;
	dt = Pn(Pgeom(0.001, 1.2, 30)).asStream;

	1000.do {|i|
		if(i%33 ==0){freq = i % 10 + 1 * 1000};
		if(i%59 ==0){serv = ~servReg.values.wrapAt(i).postcln };

		(	instrument: \grain,
			server: serv,
			out: [0,1],
			amp: 1/2,
			freq: freq + 2.0.rand2.midicps,
			sustain: 0.001 * rrand(1, 2.0)
		).play;
		dt.next.wait
	};
}).stop
)

// - 1:30:27.65 - (adc)
(type: \urlaut, fundA: 130, fundZ: 160, vowelA: \u, vowelZ: \i).play;

// - 1:30:29.18 - (adc)
(type: \urlaut, fundA: 30, fundZ: 6, dur: 5, amp: 0.2).play(b);

// - 1:30:30.18 - (adc)
(type: \urlaut, fundA: 30, fundZ: 4, dur: 10, vowelA: \e, vowelZ: \u, \amp: 1).play;

// - 1:30:30.87 - (void)
(
Tdef( 'tim' , {
	var timelist =  [ 1, 1, 1, 2, 2, 4 ];
	var sustain = 0.2;
	inf.do{|j|
		var s = ~servReg.choose;
		if(0.1.coin){ timelist = timelist.scramble};
		if(0.1.coin){ sustain = exprand(0.05, 2)};
		timelist.do { |dt, i|
			( 'freq': [260,1680], 'mod_index': 3.0, 'out': 0, 'instrument': 'SOStom',
				'pan': 0.0, 'amp': 0.1,
				server: s,
				sustain:sustain,
				'beater_noise_level': 0.025, 'decay': 1, 'mod_freq': 1.0 ).play;


			(dt / 2).wait;
		}
	}
} ).stop;
)

// - 1:30:31.12 - (adc)
(type: \urlaut, fundA: 70, fundZ: 80, vowelA: \e, vowelZ: \u, dur: 0.2, amp: 0.5, server: h).play;

// - 1:30:39.71 - (adc)
(type: \urlaut, fundA: 70, fundZ: 80, vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15).play;

// - 1:30:52.58 - (adc)
(type: \urlaut, fundA: 70, fundZ: 180, vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15).play;

// - 1:30:57.05 - (konstantinos)
		Tdef('mode_canon_1').set(\transpose, 16.rand2);

// - 1:30:58.23 - (konstantinos)
(
Tdef( 'mode_canon_1' , { |ev|
	var motif = [ [ 0, 1, 2 ], [ 0, 2, 1 ], [ 1, 0, 2 ], [ 1, 2, 0 ], [ 2, 0, 1 ], [ 2, 1, 0 ] ];
	ev.scaleName = ~commons[\canonScale];
	ev.scale = Scale.at(ev.scaleName);

	loop {
		// wait a bit before starting to play
		(~addrBook.size * 2).rand.wait;
		Tdef('mode_canon_1').set(\dt, 1/[2, 3, 4, 5, 6, 8].choose);
		Tdef('mode_canon_1').set(\octave, [4, 5, 6].choose);
		Tdef('mode_canon_1').set(\transpose, 16.rand2);
		Tdef('mode_canon_1').set(\inst, Tdef('mode_canon_1').get(\syndefs).choose);

		(0..7).do { |i|
			motif.do { |trip, j|
				trip.do { |note, k|
					(instrument:
						ev.inst,
						scale: ev.scale,
						degree: note + i + ev.transpose,
						server: ~servReg.choose,
						octave: ev.octave,
						dur: 0.5,
						amp: ev.amp
					).play;
					ev.dt.wait;
				};
				ev.dt.wait;
			};
			(ev.dt * 2).wait;
		};
	};
} );
);

// - 1:31:3.22 - (void)
(
Tdef(\hartBraten, {		// harter Braten !
	1125.do({ arg i; var frq, sus, serv;
		frq = [ 4000, 7000, 9999].choose;
		sus = 0.1;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\atk: 6,
			\sustain: sus,
			\amp: 0.25,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \grainlet,
			\freq: frq / 4,
			\atk: 3,
			\sustain: sus * 0.5,
			\amp: 0.25,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:31:6.66 - (selo)
(
// slo mo urlaut - very lo fund freqs
Pdef(\urz2,
	Pstutter(
		Prand([1, 1, 1, 1, 2], inf),
		Pbind(
			\vowelA, Pseq("aaaeeiioouu".reverse, inf),
			\vowelZ, Pseq("aaaeeiioou".reverse, inf),
			\type, \urlaut,
			\server, ~servReg.choose.postln,
			\fundA, 12,
			\fundZ, Pseq((50, 60..140) .wrap(4, 20), inf),
			\dur, Prand([1, 0.5, 0.25, 0.25, 0.130, 0.130, 0.125, 0.125]*5, inf),
			\legato, 1/(10 ** Pbrown(-1, -0.5)),
			\amp, 1
			//	\sustain, 0.9
		)
	)
).play;
)

// - 1:31:21.94 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 0.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:31:25.81 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:27.37 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:29.05 - (void)
Tdef(\hartBraten).stop;

// - 1:31:29.28 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:29.52 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 4.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:31:30.96 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:35.93 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 1.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:31:36.88 - (adc)
~s.choose

// - 1:31:37.5 - (void)
(
Pdef(\stutter,
	Pbind(
		\instrument, \UCAstutter,
		\dur, 4, //Pseq([0.25, 0.125, 0.125], inf),
		\atk, 3,
		\rel, 6,
		\amp, 0.75,
		\freq, Pseq([400, 250, 500], inf),
		\trigFreq, Pwhite(1,12),
		\server, Pfunc({(~s.values).choose}),
		\crushRate, Pwhite(50,400),
	)
).play;
)

// - 1:31:40.06 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:44.21 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:44.41 - (void)
(
Pdef(\stutter,
	Pbind(
		\instrument, \UCAstutter,
		\dur, 4, //Pseq([0.25, 0.125, 0.125], inf),
		\atk, 3,
		\rel, 6,
		\amp, 0.75,
		\freq, Pseq([4000, 2500, 5000], inf),
		\trigFreq, Pwhite(1,12),
		\server, Pfunc({(~s.values).choose}),
		\crushRate, Pwhite(50,400),
	)
).play;
)

// - 1:31:45.48 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:31:46.58 - (selo)
(
// urlaut smoother
Pdef(\ur5,
	Pstutter(
	Prand([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 5], inf),
		Pbind(
			\vowelA, Pseq("oooiiuui".scramble, inf),
			\vowelA, Pseq("iiiaioo".reverse, inf),
			\type, \urlaut,
			\voice, \counterTenor,
			\fundA, Pseq((50, 60..210), inf),
			\fundZ, Pseq( ((1,2..40) + 60).midicps , inf),
			\dur, Pseq([Pbrown(0.05, 0.15, 0.02, {15.exprand(2)} ), Prand([1,2], 1)], inf),
			\legato, (10 ** Pbrown(-0.7, 0.07, 0.07)),
			\amp, 0.1,
			\pan, 1.rand2,
		)
	)
).play;
)

// - 1:31:46.72 - (onur)
//!! too much direct blip on me

// - 1:31:46.91 - (adc)
(type: \urlaut, fundA: rrand(40, 120), fundZ: rrand(40, 120), vowelA: \e, vowelZ: \u, dur: 30, amp: 0.15, server: ~s.choose).play;

// - 1:32:2.26 - (selo)
(
Tdef(\slow2, {
	100.do({ arg i;
		(instrument: \glisson,
			\freq: i % 5 * 100 + 200,
			\freq2: i % 7 * 200 + 500,
			\sustain: 0.01,
			\server: ~servReg.values.choose
		).play;
		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:32:24.11 - (onur)
(instrument: \xf_wah, addAction: 1, dur: 6, server: s).play;

// - 1:32:26.79 - (void)
(
~servReg.do { |s|
	(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.20, drift: 0.2, rate: 0.3,
		addAction: 1, group: 1, server: s).play;
};
);

// - 1:32:30.62 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:32:32.34 - (adc)
//!! time to land - noisy

// - 1:32:33.09 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:32:39.19 - (selo)
(
Ndef(\voTell, {|pitch=90, shape=3, edge=32, reso=1, lag=2|
	var puls, form;
	var ffreqs = \ffreqs.kr({5000.rand+444}!5, lag);
	var amps = \amps.kr(0.1!5, lag);
	var qs = \qs.kr(0.1 !5, lag) * reso;

	puls = SinOsc.ar(pitch.lag(lag)).abs.pow(shape).round(1/(2**edge));
	// puls = Impulse.ar(pitch.lag(lag));
	// puls = Pulse.ar(pitch.lag(lag), shape/10%1);
	form = Formlet.ar(puls, ffreqs, qs/pi, qs, amps);
	form.mean.dup
}).play(vol: 0.5)
)

// - 1:32:40.08 - (adc)
(
// play sound once on all servers:
~servReg.values.do { |serv|
	(
				instrument: \grainXLine,
				server: serv,
	 			freq: exprand(200, 20000),
	 			sustain: 0.1,
	 			amp: 0.8
	 		).play;
};
);

(
// axisOfEvil
Tdef(\axisOfEvil).set(\hits, 20);
Tdef(\axisOfEvil, { |e|
	e.hits.do({ |i|
			(
				instrument: \grainXLine,
				server: ~servReg.choose,
	 			freq: exprand(200, 20000),
	 			sustain: 0.1,
	 			amp: 2

	 		).play;

		(rrand(1, 4) * 0.01).wait;
	});
}).play(quant: 0);
);
/*
Tdef(\axisOfEvil).set(\hits, 4).play;
Tdef(\axisOfEvil).set(\hits, 50).play;
Tdef(\axisOfEvil).set(\hits, 20).play;
*/

// - 1:32:41.91 - (adc)
(
// play sound once on all servers:
~servReg.values.do { |serv|
	(
				instrument: \grainXLine,
				server: serv,
	 			freq: exprand(200, 20000),
	 			sustain: 0.1,
	 			amp: 0.8
	 		).play;
};
);

(
// axisOfEvil
Tdef(\axisOfEvil).set(\hits, 20);
Tdef(\axisOfEvil, { |e|
	e.hits.do({ |i|
			(
				instrument: \grainXLine,
				server: ~servReg.choose,
	 			freq: exprand(200, 20000),
	 			sustain: 0.1,
	 			amp: 2

	 		).play;

		(rrand(1, 4) * 0.01).wait;
	});
}).play(quant: 0);
);
/*
Tdef(\axisOfEvil).set(\hits, 4).play;
Tdef(\axisOfEvil).set(\hits, 50).play;
Tdef(\axisOfEvil).set(\hits, 20).play;
*/

// - 1:32:42.13 - (void)
(instrument: \axf_tanh, gain: 10, dur: 50, addAction: 1, group: 1, server: s).play;

// - 1:32:45.43 - (void)
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:32:49.08 - (selo)
(
Ndef(\voTell, {|pitch=90, shape=3, edge=32, reso=1, lag=2|
	var puls, form;
	var ffreqs = \ffreqs.kr({5200.rand+444}!5, lag);
	var amps = \amps.kr(0.1!5, lag);
	var qs = \qs.kr(0.1 !5, lag) * reso;

	puls = SinOsc.ar(pitch.lag(lag)).abs.pow(shape).round(1/(2**edge));
	// puls = Impulse.ar(pitch.lag(lag));
	// puls = Pulse.ar(pitch.lag(lag), shape/10%1);
	form = Formlet.ar(puls, ffreqs, qs/pi, qs, amps);
	form.mean.dup
}).play(vol: 0.5)
)

// - 1:32:50.02 - (adc)
(
// play it on all servers, with different values
~servReg.do { |sv|
	(instrument: \xf_strobe, lofreq: exprand(13.0, 34.0), phase: 1.0.rand, sustain: rrand(3, 8),
		addAction: 1, group: 1, server: sv).play;
};
);

// - 1:32:53.99 - (adc)
(
// play it on all servers, with different values
~servReg.do { |sv|
	(instrument: \xf_strobe, lofreq: exprand(13.0, 34.0), phase: 1.0.rand, sustain: rrand(3, 8),
		addAction: 1, group: 1, server: sv).play;
};

// play it on a subgroup of servers, with different values
~servReg.values.scramble.keep(15).postln.do { |sv|
	(instrument: \xf_strobe, lofreq: exprand(5.0, 21.0), phase: 1.0.rand, sustain: 5,
		addAction: 1, group: 1, server: sv).play;
};
);

// - 1:32:58.01 - (selo)
(
Ndef(\voTell, {|pitch=20, shape=3, edge=32, reso=1, lag=2|
	var puls, form;
	var ffreqs = \ffreqs.kr({5200.rand+444}!5, lag);
	var amps = \amps.kr(0.1!5, lag);
	var qs = \qs.kr(0.1 !5, lag) * reso;

	puls = SinOsc.ar(pitch.lag(lag)).abs.pow(shape).round(1/(2**edge));
	// puls = Impulse.ar(pitch.lag(lag));
	// puls = Pulse.ar(pitch.lag(lag), shape/10%1);
	form = Formlet.ar(puls, ffreqs, qs/pi, qs, amps);
	form.mean.dup
}).play(vol: 0.5)
)

// - 1:33:2.8 - (adc)
(
// reverb with drift
~servReg.do { |s|
	(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.12, drift: 0.8, rate: 0.3,
		addAction: 1, group: 1, server: s).play;
};
);

// - 1:33:5.62 - (selo)
(
Ndef(\voTell, {|pitch=20, shape=3, edge=32, reso=1, lag=2|
	var puls, form;
	var ffreqs = \ffreqs.kr({5200.rand+444}!5, lag);
	var amps = \amps.kr(0.1!5, lag);
	var qs = \qs.kr(0.1 !5, lag) * reso;

	puls = SinOsc.ar(pitch.lag(lag)).abs.pow(shape).round(1/(2**edge));
	// puls = Impulse.ar(pitch.lag(lag));
	// puls = Pulse.ar(pitch.lag(lag), shape/10%1);
	form = Formlet.ar(puls, ffreqs, qs/pi, qs, amps);
	form.mean.dup
}).play(vol: 0.9)
)

// - 1:33:6.74 - (konstantinos)
ScIDE.defaultServer.record

// - 1:33:8.48 - (adc)
(
// noisy analog line
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;
);

// - 1:33:10.36 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:10.88 - (adc)
(
// noisy analog line
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;

// irregular noisy interference
(instrument: \xf_noizy2, rate: 5, dur: 10, addAction: 1, group: 1, server: s).play;
);

// - 1:33:13.23 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:15.13 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,18], inf),
		\ctranspose, 30,
		\yi, Pwhite(0.2, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:33:16.17 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:17.7 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:19.24 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:19.88 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:20.43 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 2.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:21.05 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 30,
		\yi, Pwhite(0.2, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.5,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:33:23.95 - (selo)
(
Tdef(\hartBraten, {		// harter Braten !
	1.do({ arg i; var frq, sus, serv;
		frq = [ 4400, 6600, 800].choose;
		sus = 0.01;
		serv = ~servReg.values.wrapAt(i.neg / 5);
		(instrument: \grain,
			\freq: frq,
			\sustain: sus,
			\amp: 4.5,
			server: serv
		).play;

		0.01.wait;
		serv = ~servReg[\manta];
		(instrument: \ana2,
			\freq: frq / 1.5,
			\sustain: sus * 1.9,
			\amp: 4.5,
			server: serv
		).play;


		([0.5, 0.1, 2, 8].choose * 0.01).wait;
	})
}).play;
)

// - 1:33:33.13 - (adc)
(
~servReg.do { |s|
	(instrument: \xf_dropTape, dt: rrand(3, 12), addAction: 1, group: 1, server: s).play;
};
);

// - 1:33:33.22 - (void)
(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.20, drift: 0.2, rate: 0.3,
		addAction: 1, group: 1, server: s).play;

// - 1:33:33.25 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:33:41.04 - (adc)
(
// reverb with drift
~servReg.do { |s|
	(instrument: \xf_rev, dur: 30, revTime: 5, wet: 0.12, drift: 0.8, rate: 0.3,
		addAction: 1, group: 1, server: s).play;
};
);

// - 1:33:41.17 - (selo)
(
Tdef(\a_DROP, {
	3.do {
		var dt = exprand(0.3, 3).round(0.01);
		var servs = ~servReg.values.scramble.keep(3);
		servs.do { |sv|
			(instrument: \dropTape, dt: dt,
				addAction: 1, group: 1, server: sv
			).postln.play;
			dt * exprand(1.0, 4.0).wait;
		};
		4.wait;
	}
});
)

// - 1:33:46.52 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 30,
		\yi, Pwhite(0.2, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.6,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:33:49.72 - (adc)
(
// wahwah pedal with distortion
~servReg.do { |s|
	(instrument: \xf_wah, addAction: 1, dur: exprand(3, 10), server: s).play;
};
);

// - 1:33:53.51 - (selo)
(
Tdef(\a_DROP, {
	3.do {
		var dt = exprand(0.3, 3).round(0.01);
		var servs = ~servReg.values.scramble.keep(3);
		servs.do { |sv|
			(instrument: \dropTape, dt: dt,
				addAction: 1, group: 1, server: sv
			).postln.play;
			dt * exprand(1.0, 5.0).wait;
		};
		4.wait;
	}
});
)

// - 1:33:54.22 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.2, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.6,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:0.11 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.6,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:7.58 - (void)
(instrument: \axf_tanh, gain: 10, dur: 50, addAction: 1, group: 1, server: s).play;

// - 1:34:11.52 - (void)
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:34:15.33 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:34:18.25 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.4,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:21.9 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.2,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:26.46 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 2,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.01,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:27.12 - (konstantinos)
Tdef.clear

// - 1:34:31.04 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 6,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.01,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:34.45 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 6,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.1,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:34:40.72 - (konstantinos)
Pdef.clear(8)

// - 1:35:2.94 - (adc)
(
Tdef(\denseFlimm, {
	100.do({ arg i;
		(instrument: \amacherFlimmern,

			\freq: i % 5 * 300 + 1000,
			\freq2: i % 7 * 200 + 2000,
			\sustain: 01.05,
			\amp: 0.5,
			\server:  ~servReg.values.choose
		).play;

		[1, 0.5, 0.5].choose.wait;
	});
}).play(quant: 0);
)

// - 1:35:5.31 - (selo)
(	// enigmatic
Tdef(\enigma, {
	4.do({ arg isx;
		Routine({
			4.do({ arg i; var frq, sus, dir, tim, serv;
				dir = [-1, 1].wrapAt(isx);
				tim = [(1/(1+i)), i].wrapAt(isx);
				frq = [ 4400, 6600, 8800].choose / (isx+1);
				sus = 0.001 * (isx+1);
				serv = ~servReg.values.wrapAt(i* dir);
				(instrument: \fifty,
					\freq: frq,
					\sustain: sus,
					\amp: 09.5,
					server: serv
				).play;

				serv = ~servReg.values.wrapAt(i* dir+ isx);
				(instrument: \bsfm,
					\freq: frq * 1.12,
					\sustain: sus / 6.3,
					\amp: 2,
					server: serv
				).play;

				( tim * 0.1).wait;
			})
		}).play;
		7.wait;
	});
}).play;
)

// - 1:35:16.42 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:35:21.16 - (selo)
(~hereDir.dirname.dirname +/+ "_utopia_snd_patches/_Utopia_Examples/*.scd").pathMatch.choose.openOS;

// - 1:35:39.93 - (onur)
//!! fade?

// - 1:35:41.81 - (adc)
//!! thin out and land

// - 1:35:51.09 - (selo)
//!! k

// - 1:35:57.46 - (void)
(instrument: \xf_noizy, noizy: 0.6, dur: 10, addAction: 1, group: 1, server: s).play;

// - 1:35:58.5 - (void)
(instrument: \axf_tanh, gain: 10, dur: 50, addAction: 1, group: 1, server: s).play;

// - 1:36:0.06 - (konstantinos)
//!! okay yes

// - 1:36:1.89 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:36:5.59 - (adc)
(
Tdef( 'gliso' , {
	100.do({ arg i;
		(
			instrument: \ana1,
			instrument: \glisson,
			\freq: i % 15 * -4 + 200 * 12,
			\freq2: i % 7 * 20 + 200 * 4,
			\sustain: 0.04,
			\amp: 0.25,
			\server:  ~servReg.values @@ i
		).postln.play;

		[0.1, 0.2, 0.4].choose.wait;
	});
} ).play;
)

// - 1:36:5.73 - (onur)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(10, 15), server: s).play;

// - 1:36:6.32 - (void)
(instrument: \xf_tanh, gain: 10, dur: 50, addAction: 1, group: 1, server: s).play;

// - 1:36:10.85 - (void)
(instrument: \xf_dropTape, addAction: 1, addAction: 1, group: 1, sustain: rrand(5, 15), server: s).play;

// - 1:36:21.19 - (konstantinos)
(
Tdef( 'gliso' , {
	100.do({ arg i;
		(
			instrument: \ana1,
			instrument: \glisson,
			\freq: i % 15 * -4 + 200 * 12,
			\freq2: i % 7 * 20 + 200 * 4,
			\sustain: 0.04,
			\amp: 0.25,
			\server:  ~servReg.values @@ i
		).postln.play;

		[0.1, 0.2, 0.4].choose.wait;
	});
} ).play;
)

// - 1:36:26.38 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 6,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.05,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:36:30.59 - (void)
(
Pdef( \white,
	Pbind(
		\instrument, \linCong,
		\dur, 6,//Pfunc({rrand(0.25, 4)}),
		\scale, Scale.hirajoshi,
		\degree, Prand([12,55], inf),
		\ctranspose, 60,
		\yi, Pwhite(0.0, 3.5),
		\atk, 4,
		\rel, 8,
		\amp, 0.002,
		\server, Pfunc({(~s.values).choose}),
		\pan, Pwhite(-0.8, 0.8, inf)))
)

// - 1:36:39.25 - (konstantinos)
(
Tdef( 'gliso' , {
	100.do({ arg i;
		(
			instrument: \ana1,
			instrument: \glisson,
			\freq: i % 15 * -4 + 200 * 12,
			\freq2: i % 7 * 20 + 200 * 4,
			\sustain: 0.04,
			\amp: 0.25,
			\server:  ~servReg.konstantinos
		).postln.play;

		[0.1, 0.2, 0.4].choose.wait;
	});
} ).play;
)

// - 1:36:40.85 - (onur)
"Cool".say(nil, \en); // choose random voice

// - 1:36:41.17 - (void)
Pdef(\white).stop(t, quant: -1);

// - 1:36:44.43 - (onur)
"Cool".say(nil, \en); // choose random voice

// - 1:36:47.82 - (onur)
"Cool".say(nil, \en); // choose random voice

// - 1:36:51.08 - (onur)
"Cool".say(nil, \en); // choose random voice

// - 1:36:54.05 - (onur)
"Cool".say(nil, \en); // choose random voice

// - 1:36:55.96 - (konstantinos)
//!! ADC can you shut?

// - 1:36:57.23 - (onur)
"Cool".say(nil, \en); // choose random voice

// - 1:37:8.11 - (konstantinos)
//!! ADC can you shut, everybody

// - 1:37:9.42 - (adc)
//!! yep

// - 1:37:20.45 - (adc)
~addrBook.peers.do(_.sendMsg("/oo_i", "s.quit"));

